services:
  backend:
    build: ./backend
    container_name: bcrss-backend
    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: bcrss-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"