services:
  - type: web
    name: bcrss-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn bcrss_config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: USE_POSTGRES
        value: "True"
      - key: DATABASE_URL
        fromDatabase:
          name: bcrss-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: bcrss-db
    plan: free
    databaseName: bcrss_db
    user: bcrss_user
