"""
Django settings for bcrss_config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY MUST be set via environment variable.
The insecure fallback is only allowed when DEBUG=True (development).
_is_dev = os.getenv('DEBUG', 'True') == 'True'
SECRET_KEY = os.getenv('SECRET_KEY', '')
if not SECRET_KEY:
    if _is_dev:
        SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise ValueError('SECRET_KEY environment variable is required in production (DEBUG=False).')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _is_dev

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'users',
    'resources',
    'jobs',
    'borrow_requests',
    'reviews',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bcrss_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bcrss_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration - uses SQLite in development, PostgreSQL (Supabase) in production
import dj_database_url
import logging

logger = logging.getLogger(__name__)

DATABASE_URL = os.getenv('DATABASE_URL', '')

def _parse_database_url(url):
    """
    Parse a DATABASE_URL that may contain unencoded special characters
    in the password (@, ?, #, etc.).  Falls back to dj_database_url when
    the URL is clean; builds the config dict manually otherwise.
    """
    import re, urllib.parse

    # --- Manual parse that handles @ and ? inside passwords ---------------
    scheme_match = re.match(r'^(postgres(ql)?://)', url)
    if scheme_match:
        scheme = scheme_match.group(1)
        rest = url[len(scheme):]
        # Match the real host@ (hostname is word-chars/dots/hyphens + optional :port + optional /path)
        host_match = re.search(r'@([a-zA-Z0-9._-]+(?::\d+)?(?:/.*)?)$', rest)
        if host_match:
            creds = rest[:host_match.start()]
            host_part = host_match.group(1)  # e.g. "db.xxx.supabase.co:5432/postgres"
            colon = creds.find(':')
            if colon != -1:
                user = urllib.parse.unquote(creds[:colon])
                password = urllib.parse.unquote(creds[colon + 1:])
                # Parse host_part → hostname, port, dbname
                hp = urllib.parse.urlparse(f'//{host_part}')
                hostname = hp.hostname or ''
                port = hp.port or 5432
                dbname = hp.path.lstrip('/') or 'postgres'
                return {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': dbname,
                    'USER': user,
                    'PASSWORD': password,
                    'HOST': hostname,
                    'PORT': port,
                    'CONN_MAX_AGE': 600,
                    'CONN_HEALTH_CHECKS': False,
                    'OPTIONS': {},
                }

    # --- Clean URL: use dj_database_url as before -------------------------
    return dj_database_url.config(url=url, conn_max_age=600,
                                  ssl_require=os.getenv('DEBUG', 'True') != 'True')

db_config = None
if DATABASE_URL:
    try:
        db_config = _parse_database_url(DATABASE_URL)
    except Exception as exc:
        logger.error('Failed to parse DATABASE_URL: %s', exc)
        db_config = None

    if not db_config or not db_config.get('NAME'):
        logger.warning('DATABASE_URL is set but could not be parsed. Falling back to SQLite.')
        db_config = None
    else:
        # Ensure Supabase-specific options
        opts = db_config.setdefault('OPTIONS', {})
        if 'sslmode' not in opts and 'sslmode' not in DATABASE_URL:
            opts.setdefault('sslmode', 'require')
        opts.setdefault('connect_timeout', 10)
        logger.info('Database connected: engine=%s host=%s name=%s',
                     db_config.get('ENGINE'), db_config.get('HOST'), db_config.get('NAME'))

if db_config:
    DATABASES = {'default': db_config}
else:
    # Fallback to SQLite when DATABASE_URL is unset, empty, or invalid
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    logger.info('Using SQLite fallback database: %s', DATABASES['default']['NAME'])


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CORS Configuration
_DEFAULT_CORS_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
    'http://localhost:80',
    'http://127.0.0.1:80',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'https://bcrss-6mxrxtkga-bcrss.vercel.app',
    'https://bcrss.vercel.app',
]

_cors_raw = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _cors_raw.strip():
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_raw.split(',') if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = _DEFAULT_CORS_ORIGINS

# SECURITY: Never allow all origins — use explicit allowlist only.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ─── Security Headers ────────────────────────────────────────
# These protect against common web attacks when behind a reverse proxy.
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Only enforce HTTPS in production
if not _is_dev:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000   # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': ['rest_framework.filters.SearchFilter', 'rest_framework.filters.OrderingFilter'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Rate limiting (throttling) to prevent brute-force attacks
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',     # Unauthenticated: 30 requests per minute
        'user': '120/minute',    # Authenticated: 120 requests per minute
        'auth': '10/minute',     # Login/register: 10 attempts per minute
    },
    'EXCEPTION_HANDLER': 'bcrss_config.exception_handlers.custom_exception_handler',
}

# Custom error handlers (JSON responses with CORS headers on 404/500)
handler404 = 'bcrss_config.exception_handlers.custom_404_handler'
handler500 = 'bcrss_config.exception_handlers.custom_500_handler'

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JTI_CLAIM': 'jti',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_IN_BLACKLIST_CLAIM': 'jti',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ATTR_NAME': 'username',
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
    'TOKEN_VERIFY_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenVerifySerializer',
    'TOKEN_BLACKLIST_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenBlacklistSerializer',
}

# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', '')

# Email Configuration (Django Email Backend)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@bcrss.com')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Frontend URL for email links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://bcrss.vercel.app')

# Authentication
AUTH_USER_MODEL = 'users.User'

# drf-spectacular (OpenAPI / Swagger)
SPECTACULAR_SETTINGS = {
    'TITLE': 'BCRSS API',
    'DESCRIPTION': 'Baraton Community Resource Sharing System — REST API for users, resources, jobs, borrow requests, and reviews.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'ResourceStatus': 'resources.models.Resource.STATUS_CHOICES',
        'ResourceCategory': 'resources.models.Resource.CATEGORY_CHOICES',
        'ResourceCondition': 'resources.models.Resource.CONDITION_CHOICES',
        'LendingType': 'resources.models.Resource.LENDING_TYPE_CHOICES',
        'JobStatus': 'jobs.models.JobOpportunity.STATUS_CHOICES',
        'JobCategory': 'jobs.models.JobOpportunity.CATEGORY_CHOICES',
        'BorrowStatus': 'borrow_requests.models.BorrowRequest.STATUS_CHOICES',
        'ReviewRole': 'reviews.models.Review.ROLE_CHOICES',
        'UserRole': 'users.models.User.ROLE_CHOICES',
        'JobApplicationStatus': 'jobs.models.JobApplication.STATUS_CHOICES',
    },
    'TAGS': [
        {'name': 'Auth', 'description': 'Registration, login, logout, password reset'},
        {'name': 'Users', 'description': 'User profiles and admin management'},
        {'name': 'Resources', 'description': 'Farm tools, textbooks, and household items'},
        {'name': 'Jobs', 'description': 'Job opportunities and applications'},
        {'name': 'Borrow Requests', 'description': 'Borrowing workflow and dispute resolution'},
        {'name': 'Reviews', 'description': 'Ratings and community feedback'},
    ],
}
