# Generated by Django 6.0.6 on 2026-07-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Skilled Trade', 'Skilled Trade'), ('Farm Work', 'Farm Work'), ('Tutoring', 'Tutoring'), ('Casual Labor', 'Casual Labor')], max_length=50)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Filled', 'Filled')], default='Open', max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Opportunity',
                'verbose_name_plural': 'Job Opportunities',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
