# Generated by manual migration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunity',
            name='requirements',
            field=models.JSONField(default=list, blank=True),
        ),
    ]
