# Generated by Django 6.0.6 on 2026-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='category',
            field=models.CharField(choices=[('Skilled Trade', 'Skilled Trade'), ('Farm Work', 'Farm Work'), ('Tutoring', 'Tutoring'), ('Casual Labor', 'Casual Labor'), ('Trade & Business', 'Trade & Business'), ('Chama Activities', 'Chama Activities')], max_length=50),
        ),
    ]
