# Generated by Django 6.0.6 on 2026-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('farm tools', 'Farm Tools'), ('textbooks', 'Textbooks'), ('household items', 'Household Items'), ('trade equipment', 'Trade Equipment'), ('chama resources', 'Chama Resources')], max_length=50),
        ),
    ]
