# Generated by Django 6.0.6 on 2026-08-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for the uploaded resource image', max_length=500, null=True),
        ),
    ]
