# Generated by Django 6.0.6 on 2026-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_requests', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='dispute_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
