# Generated by Django 6.0.6 on 2026-08-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_requests', '0004_borrowrequest_dispute_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='dispute_resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
