# Generated by Django 6.0.6 on 2026-07-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('farm tools', 'Farm Tools'), ('textbooks', 'Textbooks'), ('household items', 'Household Items')], max_length=50)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=20)),
                ('description', models.TextField()),
                ('lending_type', models.CharField(choices=[('Borrowing', 'Borrowing'), ('Donation', 'Donation')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], default='Available', max_length=20)),
                ('image_code', models.CharField(choices=[('sprayer', 'Sprayer'), ('lantern', 'Lantern'), ('biology', 'Biology'), ('plough', 'Plough'), ('computing', 'Computing'), ('wheelbarrow', 'Wheelbarrow'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('listed_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
