name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'bcrss_mobile/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd bcrss_mobile
          flutter pub get

      - name: Build Web
        run: |
          cd bcrss_mobile
          flutter build web --base-href "/BCRSS/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: bcrss_mobile/build/web
          branch: gh-pages
